### ISSUE TITLE
Fan monitoring and control not working

### ISSUE THREAD

**Issue by PearlNotHere** [OmenMon/OmenMon#22]
i have hp omen 16-wf0061tx and the fans control is not working for me , keyboard lights work just the fans not working

**Comment by PearlNotHere** [comment]
i dont know anything about coding so plz give me detailed information thnx

**Comment by originalgod11** [comment]
i am also running into this problem, everything works but fan control. leaves my fans on medium speed no matter if put it on OFF or MAX. (OMEN 16 2023 R9 4070)

**Comment by GeographicCone** [comment]
On a general note: setting arbitrary fan levels, setting fans to maximum speed, and turning them off entirely are distinct cases, handled differently. Depending on the model, one functionality might work while another won't.

For setting arbitrary fan levels, you can try enabling the [FanLevelUseEc](https://omenmon.github.io/config#fanleveluseec) setting, and possibly also [FanLevelNeedManual](https://omenmon.github.io/config#fanlevelneedmanual) in the `OmenMon.xml` [configuration file](https://omenmon.github.io/config).

The models in question are the newest gaming models though so all of these should be possible with WMI, in principle. I think someone already reported **OmenMon** to be working with a 2023 model. Could it be that the _Omen Hub_ is also setting the fan levels at the same time and interfering?

**Comment by originalgod11** [comment]
i have omenhub uninstalled and all other omen bloat disabled in Taskmanager, after a fresh install of Omenmon i still can control everything but the fans, it sits them in a medium state 24/7.

**Comment by GeographicCone** [comment]
> Try enabling the [FanLevelUseEc](https://omenmon.github.io/config#fanleveluseec) setting, and possibly also [FanLevelNeedManual](https://omenmon.github.io/config#fanlevelneedmanual) in the OmenMon.xml [configuration file](https://omenmon.github.io/config).

Have you tried this?

**Comment by GeographicCone** [comment]
All the fan control methods I'm aware of are already implemented in **OmenMon** and can be selected with the different configuration settings listed above.

I'm open to further expanding compatibility with more models but in this case it'd have to depend on someone with the hardware in question contributing a working method to control the fans.
