### ISSUE TITLE
SmartScreen warning; Refresh rate customization

### ISSUE THREAD

**Issue by atmagyan** [OmenMon/OmenMon#29]
when i right click and try to change refresh rate, i can switch to 60 but not 144, i see option for 165 but nothing happens when i click on it, also my laptop only supports 144 Hz. also smart screen warning is getting triggered with 0.60. but thanks for this amazing app, gaming hub is a mess i dont want to deal with.

**Comment by GeographicCone** [comment]
### Refresh rate

From the documentation:

> The predefined rates are controlled by the [PresetRefreshRateHigh](https://omenmon.github.io/config#presetrefreshratehigh) and [PresetRefreshRateLow](https://omenmon.github.io/config#presetrefreshratelow) configuration settings, which you should adjust to match your hardware specifications:

https://omenmon.github.io/gui#refresh-rate

> PresetRefreshRateHigh: A [numerical value](https://omenmon.github.io/config#numerical) that defaults to 165. The unit is times per second or Hertz [Hz]. Preset value to be used for [Graphics](https://omenmon.github.io/gui#menu-graphics) → [High Refresh Rate](https://omenmon.github.io/gui#refresh-rate).

https://omenmon.github.io/config#presetrefreshratehigh

### SmartScreen

See #28:

> Why can the file be flagged then? [...] It is not signed with a digital certificate — as that would only mean extra hassle for me, and something I'd likely have to shed money on

The file can be submitted to Microsoft for verification:
https://www.microsoft.com/en-us/wdsi/filesubmission

I will consider creating a Microsoft account to do this, although the issue would still resurface with every new build.

The only sure way to solve this is to purchase an Extended Validity code-signing certificate (even a standard certificate would not necessarily be enough).
