### ISSUE TITLE
omen mon在惠普中国版的暗影精灵9上无法使用

### ISSUE THREAD

**Issue by lostworldKun** [OmenMon/OmenMon#36]
在卸载ogh之后，omen的各大功能都是正常的，但是ogh卸载后把cpu的功耗和整机功耗给锁定了，omen mon无法解锁被ogh锁定的功耗

**Comment by GeographicCone** [comment]
@lostworldKun 你好，谢谢你对 OmenMon 的兴趣，虽然我看得懂中文，麻烦你在这边用英文来沟通，以便帮助来自世界各地的用户全体合作，若真的无法的话，请在最前面加上一个英文句子可以当作问题所在焦点的摘要。

因为你所提到的似乎已经有隔壁用英文描述好了，并且 GitHub 不提供议题合并的功能，我把你创建的议题先关闭，把内容搬到那边，请继续追踪议题 #37。

再次谢谢使用 OmenMon！

**Comment by GeographicCone** [comment]
Original title:
> OmenMon 在惠普中国版的暗影精灵9上无法使用

Closing as duplicate of #37. Please feel free to reopen if that's not the case.
