### ISSUE TITLE
BIOS call failed: Command not available 

### ISSUE THREAD

**Issue by SamukaGamer** [OmenMon/OmenMon#41]
Issue happens when launching GUI, changing setting to false bypasses the problem but it still does not work, only the keyboard colors

OMEN by HP 15-dc1014np (https://support.hp.com/pt-pt/product/details/omen-by-hp-15-dc1000-laptop-pc-series/model/29171025?sku=6py04ea&serialnumber=5cd929079r)

Product
6PY04EA
Series
5CD929079R

Error without translation (its in portuguese)
----------------------------------------------------------------------------------------------------------------------------------------------------
Consulte o fim desta mensagem para obter detalhes sobre como invocar a depuração 
JIT (just-in-time) em vez desta caixa de diálogo.

************** Texto da excepção **************
OmenMon.Hardware.Bios.BiosException: BIOS call failed: Command not available
   em OmenMon.Hardware.Bios.Bios.Check(Int32 code, Boolean force)
   em OmenMon.Hardware.Bios.BiosCtl.GetMaxFan()
   em OmenMon.Library.Hw.<>c__DisplayClass13_0`1.<BiosGet>b__0(IBiosCtl bios)
   em OmenMon.AppGui.GuiFormMain.UpdateFanCtl()
   em OmenMon.AppGui.GuiFormMain.UpdateAll()
   em OmenMon.AppGui.GuiFormMain..ctor()
   em OmenMon.AppGui.GuiTray.ShowFormMain()
   em System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   em System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   em System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   em System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ToolStrip.WndProc(Message& m)
   em System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblagens carregadas **************
mscorlib
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
OmenMon
    Versão da assemblagem: 0.61.0.0
    Versão Win32: 0.61.0.5020
    CodeBase: file:///C:/Users/Samuel/Downloads/OmenMon-0.61.0-Release/OmenMon.exe
----------------------------------------
System.Drawing
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Configuration
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Versão da assemblagem: 1.0.0.0
    Versão Win32: 10.0.22621.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.Management.Infrastructure.Native
    Versão da assemblagem: 1.0.0.0
    Versão Win32: 10.0.22621.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Microsoft.Management.Infrastructure.UserFilteredExceptionHandling
    Versão da assemblagem: 0.0.0.0
    Versão Win32: 10.0.22621.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Accessibility
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuração JIT **************
Para activar a depuração just-in-time (JIT), o ficheiro .config para esta
aplicação ou computador (machine.config) tem de ter o
valor jitDebugging definido na secção system.windows.forms.
A aplicação também tem de ser compilada com a depuração
activada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está activada, qualquer excepção não processada
será enviada para o depurador JIT registado no computador
em vez de ser processada por esta caixa de diálogo.
----------------------------------------------------------------------------------------------------------------------------------------------------
Error with translation using ChatGPT
----------------------------------------------------------------------------------------------------------------------------------------------------
Consult the end of this message for details on how to invoke JIT (just-in-time) debugging instead of this dialog box.

************** Exception Text **************
OmenMon.Hardware.Bios.BiosException: BIOS call failed: Command not available
   at OmenMon.Hardware.Bios.Bios.Check(Int32 code, Boolean force)
   at OmenMon.Hardware.Bios.BiosCtl.GetMaxFan()
   at OmenMon.Library.Hw.<>c__DisplayClass13_0`1.<BiosGet>b__0(IBiosCtl bios)
   at OmenMon.AppGui.GuiFormMain.UpdateFanCtl()
   at OmenMon.AppGui.GuiFormMain.UpdateAll()
   at OmenMon.AppGui.GuiFormMain..ctor()
   at OmenMon.AppGui.GuiTray.ShowFormMain()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
OmenMon
    Assembly Version: 0.61.0.0
    Win32 Version: 0.61.0.5020
    CodeBase: file:///C:/Users/Samuel/Downloads/OmenMon-0.61.0-Release/OmenMon.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.22621.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.Management.Infrastructure.Native
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.22621.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Microsoft.Management.Infrastructure.UserFilteredExceptionHandling
    Assembly Version: 0.0.0.0
    Win32 Version: 10.0.22621.1 (WinBuild.160101.0800)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/Microsoft.Management.Infrastructure.Native/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.Native.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than being handled by this dialog box.
----------------------------------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/OmenMon/OmenMon/assets/81178587/60d6f988-89f1-4cc8-8cfd-5b34e5874ecb)

If you need something I will help gladly, just tell me what to do.
Thanks.

**Comment by GeographicCone** [comment]
The relevant part is here:

> OmenMon.Hardware.Bios.BiosException: BIOS call failed: Command not available
> OmenMon.Hardware.Bios.Bios.Check(Int32 code, Boolean force)
> OmenMon.Hardware.Bios.BiosCtl.GetMaxFan()

The WMI call to get the maximum fan status is not supported by the hardware.

1. You might still be able to use maximum fan speed mode by writing to the EC:

* To enable: `OmenMon -Ec FFFF=0x0C`
* To disable: `OmenMon -Ec FFFF=0x00`
* Maybe also need to set a custom fan mode first: `OmenMon -Ec HPCM=0x31`

Does the maximum fan speed mode work for you if you try to enable it like that?

2. You might still be able to use the GUI by setting: [BiosErrorReporting](https://omenmon.github.io/config#bioserrorreporting) to **false** in `OmenMon.xml`

Other than the keyboard colors, does any of the other GUI functionality work for you?

What if you enable [FanLevelUseEc](https://omenmon.github.io/config#fanleveluseec), and maybe also [FanLevelUseManual](https://omenmon.github.io/config#fanlevelneedmanual)?

**Comment by SamukaGamer** [comment]
All fan profiles either dont do anything or are set back to default after a few seconds
CPU temperature shows 1c
And keyboard rgb works good in the GUI, but thats it, no gpu boost or cpu tdp functions or anything, just the rgb works.
Im going to try this

> You might still be able to use maximum fan speed mode by writing to the EC:
To enable: OmenMon -Ec FFFF=0x0C
To disable: OmenMon -Ec FFFF=0x00
Maybe also need to set a custom fan mode first: OmenMon -Ec HPCM=0x31
Does the maximum fan speed mode work for you if you try to enable it like that?

**Comment by SamukaGamer** [comment]
Tried using all combinations of this options from false to true

     
        <FanLevelNeedManual>true</FanLevelNeedManual>

        
        <FanLevelUseEc>true</FanLevelUseEc>

No change, fans still does not work.

![image](https://github.com/OmenMon/OmenMon/assets/81178587/c2e00df2-1aa2-48ae-a124-e6ce72f18251)

Only the RGB works, the rest either isnt available to change or just dosent apply any changes.

![image](https://github.com/OmenMon/OmenMon/assets/81178587/215592b6-5966-47df-8e84-2dc9b164c8e0)

This also does not make any changes to fan speed

![image](https://github.com/OmenMon/OmenMon/assets/81178587/1107f16b-1256-4ce2-be4b-758054cf9150)

Doing like this does not change the fans speed as well

Clicking on the taskbar icon the graphics tab does not apply any changes, only the monitor related options work, fans dont work, keyboard works all, and the rest I dont use/isnt supported by my laptop.

**Comment by SamukaGamer** [comment]
Update, after I did all this I went over to gaming hub and trid switching the power modes from cool to default and the fans are now stuck at max speed, im going to try omenmon with gaming hub uninstalled to see if it was gaming hub making the problem

**Comment by SamukaGamer** [comment]
Update 2 fans are now stuck at 100% and cant change it via any software, selecting the off option in omenmon turn them off for 2 seconds before they ramp up again to 100%

**Comment by SamukaGamer** [comment]
update 3: fixed the issue, gaming hub, omen mon and notebook fan control were unable to change fan speeds after this "bug?" the solution I did was reflashing the BIOS with an spi programmer. everything works as normal now, something got perma written on the bios somehow.

**Comment by GeographicCone** [comment]
Closing as resolved, please feel free to reopen if need be.
